### ISSUE TITLE
can you support chinese?

### ISSUE THREAD

**Issue by crusj** [alexeyco/simpletable#6]
Hello, I found this a very useful tool, but can you support Chinese, because if the table content is Chinese and the table cannot be aligned, I try to modify the realLength function in content.go and change utf8.RuneCountInString to len, but it no effect

**Comment by woosley** [comment]
@crusj  how is this solved? I am having the same issue.

**Comment by crusj** [comment]
@woosley try [https://github.com/olekukonko/tablewriter](url)

**Comment by woosley** [comment]
olekukonko/tablewrite is missing the colspan feature which I really need.
